In [1]:
import pandas as pd

In [32]:
df = pd.read_csv("data cleanning.csv")

In [5]:
df

,Student_ID,Name,Age,Gender,Marks,Attendance,Join_Date,Course
0,101,Rahul,20,M,85,90%,12-07-2023,Data Science
1,102,Anita,19,F,78,88%,15-07-2023,data science
2,103,rohan,21,m,92,95%,15-07-2023,DataScience
3,104,Priya,NaN,F,67,80%,07/16/2023,AI
4,105,Amit,twenty,M,105,110%,18-07-2023,Machine Learning
5,106,Neha,22,F,absent,85%,18-07-2023,AI
6,107,Arjun,20,M,88,NaN,19-07-2023,Machine learning
7,108,Rahul,20,M,85,90%,12-07-2023,Data Science
8,109,Kiran,23,F,73,75%,20-07-2023,AI
9,110,Sara,21,F,?,89%,21-07-2023,Data science

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  10 non-null     int64
 1   Name        10 non-null     object
 2   Age         9 non-null      object
 3   Gender      10 non-null     object
 4   Marks       10 non-null     object
 5   Attendance  9 non-null      object
 6   Join_Date   10 non-null     object
 7   Course      10 non-null     object
dtypes: int64(1), object(7)
memory usage: 772.0+ bytes

In [33]:
df['Age']= pd.to_numeric(df['Age'], errors="coerce")

In [34]:
df['Age'] = df['Age'].ffill()

In [35]:
df

,Student_ID,Name,Age,Gender,Marks,Attendance,Join_Date,Course
0,101,Rahul,20.0,M,85,90%,12-07-2023,Data Science
1,102,Anita,19.0,F,78,88%,15-07-2023,data science
2,103,rohan,21.0,m,92,95%,15-07-2023,DataScience
3,104,Priya,21.0,F,67,80%,07/16/2023,AI
4,105,Amit,21.0,M,105,110%,18-07-2023,Machine Learning
5,106,Neha,22.0,F,absent,85%,18-07-2023,AI
6,107,Arjun,20.0,M,88,NaN,19-07-2023,Machine learning
7,108,Rahul,20.0,M,85,90%,12-07-2023,Data Science
8,109,Kiran,23.0,F,73,75%,20-07-2023,AI
9,110,Sara,21.0,F,?,89%,21-07-2023,Data science

In [36]:
df['Gender'] = df['Gender'].replace({"m" : "M", "f" : "F"})

In [37]:
df

,Student_ID,Name,Age,Gender,Marks,Attendance,Join_Date,Course
0,101,Rahul,20.0,M,85,90%,12-07-2023,Data Science
1,102,Anita,19.0,F,78,88%,15-07-2023,data science
2,103,rohan,21.0,M,92,95%,15-07-2023,DataScience
3,104,Priya,21.0,F,67,80%,07/16/2023,AI
4,105,Amit,21.0,M,105,110%,18-07-2023,Machine Learning
5,106,Neha,22.0,F,absent,85%,18-07-2023,AI
6,107,Arjun,20.0,M,88,NaN,19-07-2023,Machine learning
7,108,Rahul,20.0,M,85,90%,12-07-2023,Data Science
8,109,Kiran,23.0,F,73,75%,20-07-2023,AI
9,110,Sara,21.0,F,?,89%,21-07-2023,Data science

In [38]:
df['Marks'] = pd.to_numeric(df['Marks'], errors= "coerce")

In [39]:
df

,Student_ID,Name,Age,Gender,Marks,Attendance,Join_Date,Course
0,101,Rahul,20.0,M,85.0,90%,12-07-2023,Data Science
1,102,Anita,19.0,F,78.0,88%,15-07-2023,data science
2,103,rohan,21.0,M,92.0,95%,15-07-2023,DataScience
3,104,Priya,21.0,F,67.0,80%,07/16/2023,AI
4,105,Amit,21.0,M,105.0,110%,18-07-2023,Machine Learning
5,106,Neha,22.0,F,NaN,85%,18-07-2023,AI
6,107,Arjun,20.0,M,88.0,NaN,19-07-2023,Machine learning
7,108,Rahul,20.0,M,85.0,90%,12-07-2023,Data Science
8,109,Kiran,23.0,F,73.0,75%,20-07-2023,AI
9,110,Sara,21.0,F,NaN,89%,21-07-2023,Data science

In [40]:
df.loc[(df['Marks'] > 100) | (df['Marks'] < 0), "Marks"] = pd.NA

In [41]:
df

,Student_ID,Name,Age,Gender,Marks,Attendance,Join_Date,Course
0,101,Rahul,20.0,M,85.0,90%,12-07-2023,Data Science
1,102,Anita,19.0,F,78.0,88%,15-07-2023,data science
2,103,rohan,21.0,M,92.0,95%,15-07-2023,DataScience
3,104,Priya,21.0,F,67.0,80%,07/16/2023,AI
4,105,Amit,21.0,M,NaN,110%,18-07-2023,Machine Learning
5,106,Neha,22.0,F,NaN,85%,18-07-2023,AI
6,107,Arjun,20.0,M,88.0,NaN,19-07-2023,Machine learning
7,108,Rahul,20.0,M,85.0,90%,12-07-2023,Data Science
8,109,Kiran,23.0,F,73.0,75%,20-07-2023,AI
9,110,Sara,21.0,F,NaN,89%,21-07-2023,Data science

In [42]:
df['Attendance'] = df['Attendance'].str.replace("%", "")

In [43]:
df['Attendance'] = pd.to_numeric(df['Attendance'])

In [44]:
df.loc[(df['Attendance'] > 100) | (df['Attendance'] < 0), "Attendance"] = pd.NA

In [45]:
df

,Student_ID,Name,Age,Gender,Marks,Attendance,Join_Date,Course
0,101,Rahul,20.0,M,85.0,90.0,12-07-2023,Data Science
1,102,Anita,19.0,F,78.0,88.0,15-07-2023,data science
2,103,rohan,21.0,M,92.0,95.0,15-07-2023,DataScience
3,104,Priya,21.0,F,67.0,80.0,07/16/2023,AI
4,105,Amit,21.0,M,NaN,NaN,18-07-2023,Machine Learning
5,106,Neha,22.0,F,NaN,85.0,18-07-2023,AI
6,107,Arjun,20.0,M,88.0,NaN,19-07-2023,Machine learning
7,108,Rahul,20.0,M,85.0,90.0,12-07-2023,Data Science
8,109,Kiran,23.0,F,73.0,75.0,20-07-2023,AI
9,110,Sara,21.0,F,NaN,89.0,21-07-2023,Data science

In [46]:
df['Attendance'] = df['Attendance'].fillna(df['Attendance'].median())

In [47]:
df

,Student_ID,Name,Age,Gender,Marks,Attendance,Join_Date,Course
0,101,Rahul,20.0,M,85.0,90.0,12-07-2023,Data Science
1,102,Anita,19.0,F,78.0,88.0,15-07-2023,data science
2,103,rohan,21.0,M,92.0,95.0,15-07-2023,DataScience
3,104,Priya,21.0,F,67.0,80.0,07/16/2023,AI
4,105,Amit,21.0,M,NaN,88.5,18-07-2023,Machine Learning
5,106,Neha,22.0,F,NaN,85.0,18-07-2023,AI
6,107,Arjun,20.0,M,88.0,88.5,19-07-2023,Machine learning
7,108,Rahul,20.0,M,85.0,90.0,12-07-2023,Data Science
8,109,Kiran,23.0,F,73.0,75.0,20-07-2023,AI
9,110,Sara,21.0,F,NaN,89.0,21-07-2023,Data science

In [48]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'], errors="coerce", format="mixed")

In [49]:
df

,Student_ID,Name,Age,Gender,Marks,Attendance,Join_Date,Course
0,101,Rahul,20.0,M,85.0,90.0,2023-12-07,Data Science
1,102,Anita,19.0,F,78.0,88.0,2023-07-15,data science
2,103,rohan,21.0,M,92.0,95.0,2023-07-15,DataScience
3,104,Priya,21.0,F,67.0,80.0,2023-07-16,AI
4,105,Amit,21.0,M,NaN,88.5,2023-07-18,Machine Learning
5,106,Neha,22.0,F,NaN,85.0,2023-07-18,AI
6,107,Arjun,20.0,M,88.0,88.5,2023-07-19,Machine learning
7,108,Rahul,20.0,M,85.0,90.0,2023-12-07,Data Science
8,109,Kiran,23.0,F,73.0,75.0,2023-07-20,AI
9,110,Sara,21.0,F,NaN,89.0,2023-07-21,Data science

In [50]:
df['Course'] = df['Course'].str.strip().str.lower()

In [51]:
df

,Student_ID,Name,Age,Gender,Marks,Attendance,Join_Date,Course
0,101,Rahul,20.0,M,85.0,90.0,2023-12-07,data science
1,102,Anita,19.0,F,78.0,88.0,2023-07-15,data science
2,103,rohan,21.0,M,92.0,95.0,2023-07-15,datascience
3,104,Priya,21.0,F,67.0,80.0,2023-07-16,ai
4,105,Amit,21.0,M,NaN,88.5,2023-07-18,machine learning
5,106,Neha,22.0,F,NaN,85.0,2023-07-18,ai
6,107,Arjun,20.0,M,88.0,88.5,2023-07-19,machine learning
7,108,Rahul,20.0,M,85.0,90.0,2023-12-07,data science
8,109,Kiran,23.0,F,73.0,75.0,2023-07-20,ai
9,110,Sara,21.0,F,NaN,89.0,2023-07-21,data science

In [53]:
df['Course'] = df['Course'].str.title()

In [54]:
df

,Student_ID,Name,Age,Gender,Marks,Attendance,Join_Date,Course
0,101,Rahul,20.0,M,85.0,90.0,2023-12-07,Data Science
1,102,Anita,19.0,F,78.0,88.0,2023-07-15,Data Science
2,103,rohan,21.0,M,92.0,95.0,2023-07-15,Datascience
3,104,Priya,21.0,F,67.0,80.0,2023-07-16,Ai
4,105,Amit,21.0,M,NaN,88.5,2023-07-18,Machine Learning
5,106,Neha,22.0,F,NaN,85.0,2023-07-18,Ai
6,107,Arjun,20.0,M,88.0,88.5,2023-07-19,Machine Learning
7,108,Rahul,20.0,M,85.0,90.0,2023-12-07,Data Science
8,109,Kiran,23.0,F,73.0,75.0,2023-07-20,Ai
9,110,Sara,21.0,F,NaN,89.0,2023-07-21,Data Science

In [55]:
df['Course'] = df['Course'].replace("Datascience", "Data Science")

In [56]:
df

,Student_ID,Name,Age,Gender,Marks,Attendance,Join_Date,Course
0,101,Rahul,20.0,M,85.0,90.0,2023-12-07,Data Science
1,102,Anita,19.0,F,78.0,88.0,2023-07-15,Data Science
2,103,rohan,21.0,M,92.0,95.0,2023-07-15,Data Science
3,104,Priya,21.0,F,67.0,80.0,2023-07-16,Ai
4,105,Amit,21.0,M,NaN,88.5,2023-07-18,Machine Learning
5,106,Neha,22.0,F,NaN,85.0,2023-07-18,Ai
6,107,Arjun,20.0,M,88.0,88.5,2023-07-19,Machine Learning
7,108,Rahul,20.0,M,85.0,90.0,2023-12-07,Data Science
8,109,Kiran,23.0,F,73.0,75.0,2023-07-20,Ai
9,110,Sara,21.0,F,NaN,89.0,2023-07-21,Data Science

In [59]:
df['Name'] = df['Name'].str.title()

In [60]:
df

,Student_ID,Name,Age,Gender,Marks,Attendance,Join_Date,Course
0,101,Rahul,20.0,M,85.0,90.0,2023-12-07,Data Science
1,102,Anita,19.0,F,78.0,88.0,2023-07-15,Data Science
2,103,Rohan,21.0,M,92.0,95.0,2023-07-15,Data Science
3,104,Priya,21.0,F,67.0,80.0,2023-07-16,Ai
4,105,Amit,21.0,M,NaN,88.5,2023-07-18,Machine Learning
5,106,Neha,22.0,F,NaN,85.0,2023-07-18,Ai
6,107,Arjun,20.0,M,88.0,88.5,2023-07-19,Machine Learning
7,108,Rahul,20.0,M,85.0,90.0,2023-12-07,Data Science
8,109,Kiran,23.0,F,73.0,75.0,2023-07-20,Ai
9,110,Sara,21.0,F,NaN,89.0,2023-07-21,Data Science

In [68]:
df.duplicated(subset=(["Name", "Age", "Marks", "Attendance", "Join_Date", "Course"]))

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9    False
dtype: bool

In [71]:
df = df.drop_duplicates(subset=(["Name", "Age", "Marks", "Attendance", "Join_Date", "Course"]))

In [72]:
df

,Student_ID,Name,Age,Gender,Marks,Attendance,Join_Date,Course
0,101,Rahul,20.0,M,85.0,90.0,2023-12-07,Data Science
1,102,Anita,19.0,F,78.0,88.0,2023-07-15,Data Science
2,103,Rohan,21.0,M,92.0,95.0,2023-07-15,Data Science
3,104,Priya,21.0,F,67.0,80.0,2023-07-16,Ai
4,105,Amit,21.0,M,NaN,88.5,2023-07-18,Machine Learning
5,106,Neha,22.0,F,NaN,85.0,2023-07-18,Ai
6,107,Arjun,20.0,M,88.0,88.5,2023-07-19,Machine Learning
8,109,Kiran,23.0,F,73.0,75.0,2023-07-20,Ai
9,110,Sara,21.0,F,NaN,89.0,2023-07-21,Data Science

In [79]:
df = df.drop
df = df.reset_index(drop=True)

In [80]:
df

,index,Student_ID,Name,Age,Gender,Marks,Attendance,Join_Date,Course
0,0,101,Rahul,20.0,M,85.0,90.0,2023-12-07,Data Science
1,1,102,Anita,19.0,F,78.0,88.0,2023-07-15,Data Science
2,2,103,Rohan,21.0,M,92.0,95.0,2023-07-15,Data Science
3,3,104,Priya,21.0,F,67.0,80.0,2023-07-16,Ai
4,4,105,Amit,21.0,M,NaN,88.5,2023-07-18,Machine Learning
5,5,106,Neha,22.0,F,NaN,85.0,2023-07-18,Ai
6,6,107,Arjun,20.0,M,88.0,88.5,2023-07-19,Machine Learning
7,8,109,Kiran,23.0,F,73.0,75.0,2023-07-20,Ai
8,9,110,Sara,21.0,F,NaN,89.0,2023-07-21,Data Science

In [77]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'], errors="coerce", dayfirst=True)

In [78]:
df

,index,Student_ID,Name,Age,Gender,Marks,Attendance,Join_Date,Course
0,0,101,Rahul,20.0,M,85.0,90.0,2023-12-07,Data Science
1,1,102,Anita,19.0,F,78.0,88.0,2023-07-15,Data Science
2,2,103,Rohan,21.0,M,92.0,95.0,2023-07-15,Data Science
3,3,104,Priya,21.0,F,67.0,80.0,2023-07-16,Ai
4,4,105,Amit,21.0,M,NaN,88.5,2023-07-18,Machine Learning
5,5,106,Neha,22.0,F,NaN,85.0,2023-07-18,Ai
6,6,107,Arjun,20.0,M,88.0,88.5,2023-07-19,Machine Learning
7,8,109,Kiran,23.0,F,73.0,75.0,2023-07-20,Ai
8,9,110,Sara,21.0,F,NaN,89.0,2023-07-21,Data Science

In [81]:
df = df.drop(columns=["index"])

In [82]:
df

,Student_ID,Name,Age,Gender,Marks,Attendance,Join_Date,Course
0,101,Rahul,20.0,M,85.0,90.0,2023-12-07,Data Science
1,102,Anita,19.0,F,78.0,88.0,2023-07-15,Data Science
2,103,Rohan,21.0,M,92.0,95.0,2023-07-15,Data Science
3,104,Priya,21.0,F,67.0,80.0,2023-07-16,Ai
4,105,Amit,21.0,M,NaN,88.5,2023-07-18,Machine Learning
5,106,Neha,22.0,F,NaN,85.0,2023-07-18,Ai
6,107,Arjun,20.0,M,88.0,88.5,2023-07-19,Machine Learning
7,109,Kiran,23.0,F,73.0,75.0,2023-07-20,Ai
8,110,Sara,21.0,F,NaN,89.0,2023-07-21,Data Science

In [83]:
df['Join_Date'] = df['Join_Date'].dt.strftime("%Y-%m-%d")

In [84]:
df

,Student_ID,Name,Age,Gender,Marks,Attendance,Join_Date,Course
0,101,Rahul,20.0,M,85.0,90.0,2023-12-07,Data Science
1,102,Anita,19.0,F,78.0,88.0,2023-07-15,Data Science
2,103,Rohan,21.0,M,92.0,95.0,2023-07-15,Data Science
3,104,Priya,21.0,F,67.0,80.0,2023-07-16,Ai
4,105,Amit,21.0,M,NaN,88.5,2023-07-18,Machine Learning
5,106,Neha,22.0,F,NaN,85.0,2023-07-18,Ai
6,107,Arjun,20.0,M,88.0,88.5,2023-07-19,Machine Learning
7,109,Kiran,23.0,F,73.0,75.0,2023-07-20,Ai
8,110,Sara,21.0,F,NaN,89.0,2023-07-21,Data Science