In [1]:
import pandas as pd

In [2]:
s = pd.Series([12, 65, 78, 98, 90, 56])

In [3]:
s

0    12
1    65
2    78
3    98
4    90
5    56
dtype: int64

In [5]:
print(s[0])

12

In [6]:
s2 = pd.Series([12, 65, 78, 98, 90], index = ["kedar", "shreehan", "chile", "Rugved", "raj"])

In [7]:
s2

kedar       12
shreehan    65
chile       78
Rugved      98
raj         90
dtype: int64

In [9]:
print(s2["kedar"])

12

In [12]:
print(s2["Rugved"])

98

In [13]:
type(s)

pandas.core.series.Series

In [15]:
data = {

    "name" : ["Rugved", "kedar", "shreehan"],
    "age"  : [20, 35, 10],
    "city" : ["Mumbai", "delhi", "up"]
}

In [18]:
df = pd.DataFrame(data)

In [19]:
df

       name  age    city
0    Rugved   20  Mumbai
1     kedar   35   delhi
2  shreehan   10      up

In [21]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [25]:
df.columns

Index(['name', 'age', 'city'], dtype='object')

In [26]:
data2 = [["Rugved", 69], ["kedar", 10], ["shreehan", 20]]

In [32]:
df = pd.DataFrame(data2, columns = ["Name", "Marks"])

In [33]:
df

       Name  Marks
0    Rugved     69
1     kedar     10
2  shreehan     20

In [35]:
data3 = {"a" : [3, 5, 7], "b" : [8, 9, 1]}

In [36]:
df = pd.DataFrame(data3)

In [37]:
df

   a  b
0  3  8
1  5  9
2  7  1

In [38]:
import numpy as np

In [45]:
arr = np.array([[1, 2, 3], [5, 3, 7]])

In [47]:
df = pd.DataFrame(arr, columns = ["a", "b", "c"])

In [48]:
df

   a  b  c
0  1  2  3
1  5  3  7

In [49]:
arr2 = np.array([1, 2, 3, 4])

In [52]:
df = pd.DataFrame(arr2, columns = ["A"])

In [53]:
df

   A
0  1
1  2
2  3
3  4

In [54]:
df = pd.read_excel("data.xlsx")

In [55]:
df

       Name school  marks
0   shubham    BBK     25
1    rugved    TFC     85
2     kedar    EDC      8
3    joshua    HFD     97
4  shreehan    NYG     46
5      alex    JYH     15
6     illia    BGV     74
7     islam    YGF    100

In [56]:
df = pd.read_csv("data.csv")

In [57]:
df

       Name school  marks
0   shubham    BBK     25
1    rugved    TFC     85
2     kedar    EDC      8
3    joshua    HFD     97
4  shreehan    NYG     46
5      alex    JYH     15
6     illia    BGV     74
7     islam    YGF    100

In [76]:
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")

In [77]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [62]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [63]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [65]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [66]:
df.shape

(244, 7)

df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [78]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]