In [2]:
import pandas as pd
df = pd.read_csv('Cricket_data.csv')

In [3]:
df

,season,id,name,short_name,description,home_team,away_team,toss_won,decision,1st_inning_score,...,home_playx1,away_playx1,away_key_batsman,away_key_bowler,match_days,umpire1,umpire2,tv_umpire,referee,reserve_umpire
0,NaN,1370350,Chennai Super Kings v Gujarat Titans,CSK v GT,"Qualifier 1 (N), Indian Premier League at Chen...",CSK,GT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1370351,Lucknow Super Giants v Mumbai Indians,LSG v MI,"Eliminator (N), Indian Premier League at Chenn...",LSG,MI,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,1370352,TBC v TBC,TBC v TBC,"Qualifier 2 (N), Indian Premier League at Ahme...",TBA,TBA,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,1370353,TBC v TBC,TBC v TBC,"Final (N), Indian Premier League at Ahmedabad,...",TBA,TBA,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023.0,1359544,Royal Challengers Bangalore v Gujarat Titans,RCB v GT,"70th Match (N), Indian Premier League at Benga...",RCB,GT,GT,BOWL FIRST,197/5,...,"Virat Kohli (UKN),Faf du Plessis (UKN),Glenn M...","Wriddhiman Saha (WK),Shubman Gill (UKN),Vijay ...","Shubman Gill,Vijay Shankar","Noor Ahmad,Rashid Khan",21 May 2023 - night match (20-over match),Nitin Menon,Virender Sharma,Tapan Sharma,Javagal Srinath,VM Dhokre
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027,2008.0,336012,Royal Challengers Bangalore v Mumbai Indians,RCB v MI,"55th match (D/N), Indian Premier League at Ben...",RCB,MI,MI,BOWL FIRST,122/9,...,"Mark Boucher (BT),Shreevats Goswami (WK),Misba...","Sanath Jayasuriya (AR),Sachin Tendulkar (BT),R...","Sanath Jayasuriya,Sachin Tendulkar","Dilhara Fernando,Dwayne Smith",28 May 2008 - day/night match (20-over match),Billy Bowden,Arani Jayaprakash,Billy Doctrove,Sir Clive Lloyd,NaN
1028,2008.0,336019,Kings XI Punjab v Rajasthan Royals,KXIP v RR,"56th match (N), Indian Premier League at Mohal...",KXIP,RR,RR,BOWL FIRST,221/3,...,"Shaun Marsh (BT),James Hopes (AR),Yuvraj Singh...","Mohammad Kaif (BT),Niraj Patel (UKN),Younis Kh...","Niraj Patel,Yusuf Pathan","Shane Watson,Yusuf Pathan",28 May 2008 - night match (20-over match),Krishna Hariharan,Steve Davis,Daryl Harper,Srinivas Venkataraghavan,MS Mahal
1029,2008.0,336038,Delhi Daredevils v Rajasthan Royals,DC v RR,"1st Semi-Final (N), Indian Premier League at M...",DC,RR,DC,BOWL FIRST,192/9,...,"Gautam Gambhir (BT),Virender Sehwag (BT),Shikh...","Graeme Smith (BT),Swapnil Asnodkar (BT),Sohail...","Shane Watson,Yusuf Pathan","Shane Watson,Munaf Patel",30 May 2008 - night match (20-over match),Billy Bowden,Rudi Koertzen,Billy Doctrove,Javagal Srinath,NaN
1030,2008.0,336039,Chennai Super Kings v Kings XI Punjab,CSK v KXIP,"2nd Semi-Final (N), Indian Premier League at M...",CSK,KXIP,KXIP,BAT FIRST,112/8,...,"Parthiv Patel (WK),Vidyut Sivaramakrishnan (UK...","Shaun Marsh (BT),James Hopes (AR),Kumar Sangak...","Ramesh Powar,Wilkin Mota","Irfan Pathan,Vikram Singh",31 May 2008 - night match (20-over match),Asad Rauf,Daryl Harper,Krishna Hariharan,Srinivas Venkataraghavan,NaN
1031,2008.0,336040,Chennai Super Kings v Rajasthan Royals,CSK v RR,"Final (N), Indian Premier League at Mumbai, Ju...",CSK,RR,RR,BOWL FIRST,163/5,...,"Parthiv Patel (WK),Vidyut Sivaramakrishnan (UK...","Niraj Patel (UKN),Swapnil Asnodkar (BT),Kamran...","Yusuf Pathan,Swapnil Asnodkar","Yusuf Pathan,Shane Watson",1 June 2008 - night match (20-over match),Billy Bowden,Rudi Koertzen,Daryl Harper,Javagal Srinath,MR Singh

In [4]:
df.head()

,season,id,name,short_name,description,home_team,away_team,toss_won,decision,1st_inning_score,...,home_playx1,away_playx1,away_key_batsman,away_key_bowler,match_days,umpire1,umpire2,tv_umpire,referee,reserve_umpire
0,NaN,1370350,Chennai Super Kings v Gujarat Titans,CSK v GT,"Qualifier 1 (N), Indian Premier League at Chen...",CSK,GT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1370351,Lucknow Super Giants v Mumbai Indians,LSG v MI,"Eliminator (N), Indian Premier League at Chenn...",LSG,MI,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,1370352,TBC v TBC,TBC v TBC,"Qualifier 2 (N), Indian Premier League at Ahme...",TBA,TBA,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,1370353,TBC v TBC,TBC v TBC,"Final (N), Indian Premier League at Ahmedabad,...",TBA,TBA,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023.0,1359544,Royal Challengers Bangalore v Gujarat Titans,RCB v GT,"70th Match (N), Indian Premier League at Benga...",RCB,GT,GT,BOWL FIRST,197/5,...,"Virat Kohli (UKN),Faf du Plessis (UKN),Glenn M...","Wriddhiman Saha (WK),Shubman Gill (UKN),Vijay ...","Shubman Gill,Vijay Shankar","Noor Ahmad,Rashid Khan",21 May 2023 - night match (20-over match),Nitin Menon,Virender Sharma,Tapan Sharma,Javagal Srinath,VM Dhokre

In [5]:
pd.set_option('display.max_columns', None)

In [6]:
df

,season,id,name,short_name,description,home_team,away_team,toss_won,decision,1st_inning_score,2nd_inning_score,winner,result,start_date,end_date,venue_id,venue_name,home_captain,away_captain,pom,points,super_over,home_overs,home_runs,home_wickets,home_boundaries,away_overs,away_runs,away_wickets,away_boundaries,highlights,home_key_batsman,home_key_bowler,home_playx1,away_playx1,away_key_batsman,away_key_bowler,match_days,umpire1,umpire2,tv_umpire,referee,reserve_umpire
0,NaN,1370350,Chennai Super Kings v Gujarat Titans,CSK v GT,"Qualifier 1 (N), Indian Premier League at Chen...",CSK,GT,NaN,NaN,NaN,NaN,GT,Starts at 19:30 local time,2023-05-23T14:00Z,2023-05-24T23:59Z,58008,"MA Chidambaram Stadium, Chepauk, Chennai",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1370351,Lucknow Super Giants v Mumbai Indians,LSG v MI,"Eliminator (N), Indian Premier League at Chenn...",LSG,MI,NaN,NaN,NaN,NaN,MI,Starts at 19:30 local time,2023-05-24T14:00Z,2023-05-25T23:59Z,58008,"MA Chidambaram Stadium, Chepauk, Chennai",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,1370352,TBC v TBC,TBC v TBC,"Qualifier 2 (N), Indian Premier League at Ahme...",TBA,TBA,NaN,NaN,NaN,NaN,TBA,Starts at 19:30 local time,2023-05-26T14:00Z,2023-05-27T23:59Z,57851,"Narendra Modi Stadium, Motera, Ahmedabad",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,1370353,TBC v TBC,TBC v TBC,"Final (N), Indian Premier League at Ahmedabad,...",TBA,TBA,NaN,NaN,NaN,NaN,TBA,Starts at 19:30 local time,2023-05-28T14:00Z,2023-05-29T23:59Z,57851,"Narendra Modi Stadium, Motera, Ahmedabad",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023.0,1359544,Royal Challengers Bangalore v Gujarat Titans,RCB v GT,"70th Match (N), Indian Premier League at Benga...",RCB,GT,GT,BOWL FIRST,197/5,198/4,GT,Titans won by 6 wkts (5b rem),2023-05-21T14:00Z,2023-05-22T23:59Z,57897,"M.Chinnaswamy Stadium, Bengaluru",Faf du Plessis,Hardik Pandya,Shubman Gill,"Gujarat Titans 2, Royal Challengers Bangalore 0",False,20.0,197.0,5.0,28.0,19.1,198.0,4.0,25.0,Gill's second straight century trumps Kohli's ...,"Virat Kohli,Faf du Plessis","Mohammed Siraj,Harshal Patel","Virat Kohli (UKN),Faf du Plessis (UKN),Glenn M...","Wriddhiman Saha (WK),Shubman Gill (UKN),Vijay ...","Shubman Gill,Vijay Shankar","Noor Ahmad,Rashid Khan",21 May 2023 - night match (20-over match),Nitin Menon,Virender Sharma,Tapan Sharma,Javagal Srinath,VM Dhokre
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027,2008.0,336012,Royal Challengers Bangalore v Mumbai Indians,RCB v MI,"55th match (D/N), Indian Premier League at Ben...",RCB,MI,MI,BOWL FIRST,122/9,126/1,MI,Mum Indians won by 9 wickets (with 12 balls re...,2008-05-28T10:30Z,2008-05-30T23:59Z,57897,"M.Chinnaswamy Stadium, Bengaluru",Rahul Dravid,Sachin Tendulkar,Dilhara Fernando,"Mumbai Indians 2, Royal Challengers Bangalore 0",False,18.0,122.0,9.0,13.0,16.0,126.0,1.0,16.0,Mumbai end IPL campaign with easy win. Mumbai ...,"Cameron White,Vinay Kumar","Dale Steyn,Balachandra Akhil","Mark Boucher (BT),Shreevats Goswami (WK),Misba...","Sanath Jayasuriya (AR),Sachin Tendulkar (BT),R...","Sanath Jayasuriya,Sachin Tendulkar","Dilhara Fernando,Dwayne Smith",28 May 2008 - day/night match (20-over match),Billy Bowden,Arani Jayaprakash,Billy Doctrove,Sir Clive Lloyd,NaN
1028,2008.0,336019,Kings XI Punjab v Rajasthan Royals,KXIP v RR,"56th match (N), Indian Premier League at Mohal...",KXIP,RR,RR,BOWL FIRST,221/3,180/7,KXIP,Kings XI won by 41 runs,2008-05-28T14:30Z,2008-05-30T23:59Z,57991,"Punjab Cricket Association IS Bindra Stadium, ...",Yuvraj Singh,Shane Watson,Shaun Marsh,"Kings XI Punjab 2, Rajasthan Royals 0",False,20.0,221.0,3.0,34.0,20.0,180.0,7.0,26.0,Marsh century conquers Rajasthan. Kings XI Pun...,"Shaun Marsh,James Hopes","Piyush Chawla,James Hopes","Shaun Marsh (BT),James Hopes (AR),Yuvraj Singh...","Mohammad Kaif (BT),Niraj Patel (UKN),Younis Kh...","Niraj Patel,Yusuf Pathan","Shane Watson,Yusuf Pathan",28 May 2008 - night match (20-over match),Krishna Hariharan,Steve Davis,Daryl Harper,Srinivas Venkataraghavan,MS Mahal
1029,2008.0,336038,Delhi Daredevils v Rajasthan Royals,DC v RR,"1st Semi-Final (N), Indian Premier League at M...",DC,RR,DC,BOWL FIRST,192/9,87,RR,Royals won by 105 runs,2008-05-30T14:30Z,2008-06-01T23:59Z,58324,"Wankhede Stadium, Mumbai",Virender Sehwag,Shane Warne,Shane Watson,NaN,False,16.1,87.0,10.0,10.0,20.0,192.0,9.0,29.0,Watson helps Rajasthan march into final. This ...,"Tillakaratne Dilshan,Gautam Gambhir","Farveez Maharoof,Amit Mishra","Gautam Gambhir (BT),Virender Sehwag (BT),Shikh...","Graeme Smith (BT),Swapnil Asnodkar (BT),Sohail...","Shane Watson,Yusuf Pathan","Shane Watson,Munaf Patel",30 May 2008 - night match (20-over match),Billy Bowden,Rudi Koertzen,Billy Doctrove,Javagal Srinath,NaN
1030,2008.0,336039,Chennai Super Kings v Kings XI Punjab,CSK v KXIP,"2nd Semi-Final (N), Indian Premier League at M...",CSK,KXIP,KXIP,BAT FIRST,112/8,116/1,CSK,Super Kings won by 9 wickets (with 31 balls re...,2008-05-31T14:30Z,2008-06-02T23:59Z,58324,"Wankhede Stadium, Mumbai",MS Dhoni,Yuvraj Singh,Makhaya Ntini,NaN,False,14.5,116.0,1.0,17.0,20.0,112.0,8.0,13.0,Inspired Chennai send Punjab packing. An inspi...,"Suresh Raina,Parthiv Patel","Manpreet Gony,Makhaya Ntini","Parthiv Patel (WK),Vidyut Sivaramakrishnan (UK...","Shaun Marsh (BT),James Hopes (AR),Kumar Sangak...","Ramesh Powar,Wilkin Mota","Irfan Pathan,Vikram Singh",31 May 2008 - night match (20-over match),Asad Rauf,Daryl Harper,Krishna Hariharan,Srinivas Venkataraghavan,NaN
1031,2008.0,336040,Chennai Super Kings v Rajasthan Royals,CSK v RR,"Final (N), Indian Premier League at Mumbai, Ju...",CSK,RR,RR,BOWL FIRST,163/5,164/7,RR,Royals won by 3 wickets (with 0 balls remaining),2008-06-01T14:45Z,2008-06-03T23:59Z,343050,"Dr DY Patil Sports Academy, Mumbai",MS Dhoni,Shane Warne,Yusuf Pathan,NaN,False,20.0,163.0,5.0,16.0,20.0,164.0,7.0,17.0,Rajasthan champions after cliffhanger. League ...,"Suresh Raina,Parthiv Patel","Albie Morkel,Muttiah Muralitharan","Parthiv Patel (WK),Vidyut Sivaramakrishnan (UK...","Niraj Patel (UKN),Swapnil Asnodkar (BT),Kamran...","Yusuf Pathan,Swapnil Asnodkar","Yusuf Pathan,Shane Watson",1 June 2008 - night match (20-over match),Billy Bowden,Rudi Koertzen,Daryl Harper,Javagal Srinath,MR Singh

In [7]:
df.head()

,season,id,name,short_name,description,home_team,away_team,toss_won,decision,1st_inning_score,2nd_inning_score,winner,result,start_date,end_date,venue_id,venue_name,home_captain,away_captain,pom,points,super_over,home_overs,home_runs,home_wickets,home_boundaries,away_overs,away_runs,away_wickets,away_boundaries,highlights,home_key_batsman,home_key_bowler,home_playx1,away_playx1,away_key_batsman,away_key_bowler,match_days,umpire1,umpire2,tv_umpire,referee,reserve_umpire
0,NaN,1370350,Chennai Super Kings v Gujarat Titans,CSK v GT,"Qualifier 1 (N), Indian Premier League at Chen...",CSK,GT,NaN,NaN,NaN,NaN,GT,Starts at 19:30 local time,2023-05-23T14:00Z,2023-05-24T23:59Z,58008,"MA Chidambaram Stadium, Chepauk, Chennai",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1370351,Lucknow Super Giants v Mumbai Indians,LSG v MI,"Eliminator (N), Indian Premier League at Chenn...",LSG,MI,NaN,NaN,NaN,NaN,MI,Starts at 19:30 local time,2023-05-24T14:00Z,2023-05-25T23:59Z,58008,"MA Chidambaram Stadium, Chepauk, Chennai",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,1370352,TBC v TBC,TBC v TBC,"Qualifier 2 (N), Indian Premier League at Ahme...",TBA,TBA,NaN,NaN,NaN,NaN,TBA,Starts at 19:30 local time,2023-05-26T14:00Z,2023-05-27T23:59Z,57851,"Narendra Modi Stadium, Motera, Ahmedabad",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,1370353,TBC v TBC,TBC v TBC,"Final (N), Indian Premier League at Ahmedabad,...",TBA,TBA,NaN,NaN,NaN,NaN,TBA,Starts at 19:30 local time,2023-05-28T14:00Z,2023-05-29T23:59Z,57851,"Narendra Modi Stadium, Motera, Ahmedabad",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023.0,1359544,Royal Challengers Bangalore v Gujarat Titans,RCB v GT,"70th Match (N), Indian Premier League at Benga...",RCB,GT,GT,BOWL FIRST,197/5,198/4,GT,Titans won by 6 wkts (5b rem),2023-05-21T14:00Z,2023-05-22T23:59Z,57897,"M.Chinnaswamy Stadium, Bengaluru",Faf du Plessis,Hardik Pandya,Shubman Gill,"Gujarat Titans 2, Royal Challengers Bangalore 0",False,20.0,197.0,5.0,28.0,19.1,198.0,4.0,25.0,Gill's second straight century trumps Kohli's ...,"Virat Kohli,Faf du Plessis","Mohammed Siraj,Harshal Patel","Virat Kohli (UKN),Faf du Plessis (UKN),Glenn M...","Wriddhiman Saha (WK),Shubman Gill (UKN),Vijay ...","Shubman Gill,Vijay Shankar","Noor Ahmad,Rashid Khan",21 May 2023 - night match (20-over match),Nitin Menon,Virender Sharma,Tapan Sharma,Javagal Srinath,VM Dhokre

In [8]:
df.isnull().sum()

season               5
id                   0
name                 0
short_name           0
description          0
home_team            0
away_team            0
toss_won             5
decision             5
1st_inning_score    13
2nd_inning_score    15
winner               1
result               0
start_date           0
end_date             0
venue_id             0
venue_name           0
home_captain         5
away_captain         5
pom                 17
points              65
super_over           5
home_overs          13
home_runs           13
home_wickets        13
home_boundaries     13
away_overs          15
away_runs           15
away_wickets        15
away_boundaries     15
highlights          27
home_key_batsman    13
home_key_bowler     26
home_playx1          5
away_playx1          5
away_key_batsman    15
away_key_bowler     24
match_days           5
umpire1              5
umpire2              5
tv_umpire            7
referee              5
reserve_umpire      31
dtype: int64